### ISSUE TITLE
problem with GTK theme

### ISSUE THREAD

**Issue by go-ten** [flathub/de.haeckerfelix.Shortwave#13] opened 2021-05-21 11:39 UTC
Hello, 

The application has a problem with the GTK theme.

Here are 2 flatpaks with the Yaru theme.

![image](https://user-images.githubusercontent.com/47599241/119131379-b1927600-ba39-11eb-9f45-a89bf2e51e7b.png)

Do you have any idea ?

Thks

**Comment by bilelmoussaoui** [comment] 2021-05-21 11:44
one is gtk4 and the other one is gtk3

**Comment by go-ten** [comment] 2021-05-21 11:52
So we have to wait until the yaru theme is ported to GTK 4 and available on flatpak ?

**Comment by bilelmoussaoui** [comment] 2021-05-21 12:10
> So we have to wait until the yaru theme is ported to GTK 4 and available on flatpak ?

There's no gtk4 theme flatpak extension

**Comment by go-ten** [comment] 2021-05-21 12:23
So unless you stay in the standard theme, there will always be a theme mismatch, as long as the applications are not ported to GTK 4.

**Comment by haecker-felix** [comment] 2021-05-21 12:36
Duplicate of 

https://gitlab.gnome.org/World/Shortwave/-/issues/565

and 

https://gitlab.gnome.org/World/Shortwave/-/issues/563

**Closed by haecker-felix** 2021-05-21 12:36 UTC

**Comment by go-ten** [comment] 2021-05-21 16:02
Hi,

For info, using the GTK_Theme variable does not work with Yaru Theme.

You can safely close this problem and continue to ignore this kind of bug. However, as a user, we have to care about QT and GTK applications. Now we also have to worry about GTK3 and GTK4 applications.

Why not

**Comment by bilelmoussaoui** [comment] 2021-05-21 16:16
Because there's no Yaru theme for gtk4 .....

**Comment by go-ten** [comment] 2021-05-21 16:21
Understand, I will wait for the update of yaru.

Thanks à lot
